
services:
  parsedmarc-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parsedmarc-processor
    env_file:
      - .env  
    volumes:
      - ./logs:/logs
      - ./credentials.json:/app/credentials.json:ro
      - ./token.pickle:/app/token.pickle
      - ./parsedmarc.ini:/app/parsedmarc.ini:ro
      - ./postmark.conf:/app/postmark.conf:ro
      - ./dmarc_reports:/app/dmarc_reports
    restart: unless-stopped
    network_mode: host
